Check if x-terminal-emulator is terminator
Pathoschild/SMAPI pull request #425
Opened 2018-01-15 22:15 UTC by EnderHDMC

This pull request is meant to fix #294 it just checks the what x-terminal-terminal emulator links to (which should link to: "/etc/alternatives/x-terminal-emulator") which in turn links to the executable of the shell set in update-alternatives.

2018-01-17 05:41 UTC, Pathoschild requested changes
Thanks! I like this approach. Just a few points of feedback. :)

2018-01-17 05:41 UTC, Pathoschild commented on src/SMAPI/unix-launcher.sh
> +        if [[ " $(readlink $(readlink /usr/bin/x-terminal-emulator))" == *"/terminator" ]]; then
I suggest resolving symlinks recursively and using `which` to minimise expectations:
```bash
if [[ " $(readlink -f $(which x-terminal-emulator))" == *"/terminator" ]]; then
```

Two questions here:
* Is the space at the start of the string intentional?
* Can we use the POSIX `[ ]` instead of Bash `[[ ]]` for crossplatform compatibility?

2018-01-19 17:37 UTC, EnderHDMC commented on src/SMAPI/unix-launcher.sh
> +        if [[ " $(readlink $(readlink /usr/bin/x-terminal-emulator))" == *"/terminator" ]]; then
The space was just a force of habit, since when I check things like the $PATH variable I want consistency so it's easy to process. Except with the path I add a semicolon instead of a space.
The space can be safely removed.

Also, I think the startup script is already not posix compliant.
Since `if [ "$UNAME" == "Darwin" ]; then` doesn't work on posix.
On posix it should be the same just instead of == it should just be =.
Like this: `if [ "$UNAME" = "Darwin" ]; then`

Also with the startup script it already uses a shebang to tell the program loader to use bash as the interpreter

2018-01-20 02:25 UTC, Pathoschild commented on src/SMAPI/unix-launcher.sh
> +        if [[ " $(readlink $(readlink /usr/bin/x-terminal-emulator))" == *"/terminator" ]]; then
Thanks! I added the changes (with `-e` instead of `-f`), and you're right about the POSIX compliance.

2018-01-20 02:25 UTC, Pathoschild approved these changes

2018-01-20 02:30 UTC, merged

2018-01-20 02:30 UTC, Pathoschild commented
Merged into `develop` for the upcoming SMAPI 2.4. Thanks!