Make pufferchick cool when user hovers over the download button
Pathoschild/SMAPI pull request #477
Opened 2018-04-23 06:10 UTC by danvolchek

This pull request makes the pufferchick on the index page turn into a cool pufferchick when the user hovers over the SMAPI download link. Here's it in action:

![example](https://i.imgur.com/ilvbX0C.gif)

2018-04-23 06:24 UTC, Pathoschild requested changes

2018-04-23 06:24 UTC, Pathoschild commented on src/SMAPI.Web/wwwroot/Content/js/index.js
> +    for (var downloadLink of downloadLinks) {
Unfortunately `for..of` isn't supported in IE, which still has a lot of market share. We should consider using a classic `for` here, or jQuery's `forEach`. (We already use jQuery on the log page.) I can make that change when I merge the PR though, if you want.

2018-04-23 06:55 UTC, danvolchek commented on src/SMAPI.Web/wwwroot/Content/js/index.js
> +    for (var downloadLink of downloadLinks) {
I wasn't sure that we wanted to include jQuery for just these changes, but I've gone that route. As a bonus, the document ready check is also now compatible with more browsers.

2018-04-25 16:07 UTC, Pathoschild approved these changes

2018-04-25 16:08 UTC, merged

2018-04-25 16:12 UTC, Pathoschild commented
Merged into `develop` for the upcoming SMAPI 2.6. Thanks!