set daysPlayed in world_set{day,season,year} commands
Pathoschild/SMAPI pull request #708
Opened 2020-04-10 19:46 UTC by kdau

A correctly-seeded garbage can RNG is a happy RNG.

2020-04-11 16:11 UTC, Pathoschild requested changes

2020-04-11 16:11 UTC, Pathoschild commented on src/SMAPI.Mods.ConsoleCommands/Framework/Commands/World/SetDayCommand.cs
> +            Game1.stats.DaysPlayed = (uint)(Game1.dayOfMonth + 28 * (Utility.getSeasonNumber(Game1.currentSeason) + 4 * (Game1.year - 1)));
We should use SMAPI's date wrapper instead of repeating the calculations here:
```cs
// current
Game1.stats.DaysPlayed = (uint)(Game1.dayOfMonth + 28 * (Utility.getSeasonNumber(Game1.currentSeason) + 4 * (Game1.year - 1)));

// suggested
Game1.stats.DaysPlayed = SDate.Now().DaysSinceStart;
```

2020-04-11 20:31 UTC, kdau commented on src/SMAPI.Mods.ConsoleCommands/Framework/Commands/World/SetDayCommand.cs
> +            Game1.stats.DaysPlayed = (uint)(Game1.dayOfMonth + 28 * (Utility.getSeasonNumber(Game1.currentSeason) + 4 * (Game1.year - 1)));
Done. For some reason I was thinking SDate had the same off-by-one issue with its total-days property that the game's WorldDate has, but no.

2020-04-12 01:02 UTC, Pathoschild approved these changes

2020-04-12 01:02 UTC, merged

2020-04-12 01:02 UTC, Pathoschild commented
Thanks! Merged into `develop` for the next SMAPI update.