Changing .sh to 'comply' with shellcheck
Pathoschild/SMAPI pull request #866
Opened 2022-07-26 02:22 UTC by ishanjalan

https://github.com/koalaman/shellcheck/

2022-07-26 03:20 UTC, jltaylor-us commented on src/SMAPI.Installer/assets/unix-launcher.sh
> +                    exec "$TERMINAL_NAME" env TERM=xterm $LAUNCH_FILE "$*"
changing from `"$@"` to `"$*"` is almost certainly incorrect, but as long as no one ever puts spaces inside the an argument then no one will notice.

(The mac script generation is broken in a similar way, but it was already broken.  The right way to escape things going into the new script is with the `%q` format specifier to the bash `printf` builtin.)

2022-07-26 03:20 UTC, jltaylor-us commented on build/unix/prepare-install-package.sh
> +cd "$(dirname "$0")/../.." || exit
Exiting in an error condition with no error message isn't great; exiting with a "success" exit code is worse.

It doesn't look like these files do any other sort of error checking to make sure commands succeeded.  If you want to add return status checking then `set -e` might be a better approach.

2022-07-29 01:43 UTC, Pathoschild requested changes

2022-07-29 01:43 UTC, Pathoschild commented on build/unix/prepare-install-package.sh
> +        dotnet publish src/SMAPI.Mods."$modName" --configuration $buildConfig -v minimal --runtime "$runtime" -p:OS="$msbuildPlatformName" -p:GamePath="$gamePath" -p:CopyToGameFolder="false"
Shouldn't we just quote the whole argument?
```suggestion
        dotnet publish "src/SMAPI.Mods.$modName" --configuration $buildConfig -v minimal --runtime "$runtime" -p:OS="$msbuildPlatformName" -p:GamePath="$gamePath" -p:CopyToGameFolder="false"
```

2022-07-29 01:43 UTC, Pathoschild commented on build/unix/prepare-install-package.sh
> +        if [ $name == "StardewModdingAPI" ] && [ "$folder" == "windows" ]; then
Shouldn't `$name` be quoted too while we're at it?
```suggestion
        if [ "$name" == "StardewModdingAPI" ] && [ "$folder" == "windows" ]; then
```

2022-07-29 01:43 UTC, Pathoschild commented on build/unix/prepare-install-package.sh
> +        #https://github.com/koalaman/shellcheck/wiki/SC2035 this should be either ./* or -- *
Unneeded comment:
```suggestion
```

2022-07-29 01:43 UTC, Pathoschild commented on src/SMAPI.Installer/assets/install on Linux.sh
> +cd "$(dirname "$0")" || exit
If we're going to handle all these possible error edge cases, we should log an error message indicating what failed too.

2022-07-29 01:43 UTC, Pathoschild commented on src/SMAPI.Installer/assets/unix-launcher.sh
> +                    exec "$TERMINAL_NAME" env TERM=xterm $LAUNCH_FILE "$*"
Spaces in Steam command-line arguments are certainly possible.

2022-07-29 02:06 UTC, Pathoschild commented
List of included fixes per discussion with @ishanjalan:

level | suggested fix
---- | -------------
error | [Double quote array expansions to avoid re-splitting elements.](https://github.com/koalaman/shellcheck/wiki/SC2068)
warn | [use `... \|\| exit` or `... \|\| return` in case command fails.](https://github.com/koalaman/shellcheck/wiki/SC2164)
hint | [read without -r will mangle backslashes.](https://github.com/koalaman/shellcheck/wiki/SC2162)
hint | [Use `$(...)` notation instead of legacy backticked \`...\`.](https://github.com/koalaman/shellcheck/wiki/SC2006)
hint | [Double quote to prevent globbing and word splitting.](https://github.com/koalaman/shellcheck/wiki/SC2086)
hint | [Use `./*glob*` or `-- *glob*` so names with dashes won't become options.](https://github.com/koalaman/shellcheck/wiki/SC2035)

2022-07-29 02:19 UTC, Pathoschild commented on src/SMAPI.Installer/assets/unix-launcher.sh
> +                    exec "$TERMINAL_NAME" env TERM=xterm $LAUNCH_FILE "$*"
Spaces in Steam command-line arguments are certainly possible.

Based on [the wiki page for the suggested fix](https://github.com/koalaman/shellcheck/wiki/SC2145), `$@` seems to be correct for the way we're using it. We're not appending it to a word, so the quirks don't apply in this case.

2022-10-09 16:20 UTC, Pathoschild commented
@ishanjalan I'll close this PR since it changes too many different things at once, and it still has some unresolved comments. Feel free to submit smaller PRs that change specific things so they can be discussed separately. Sorry for the inconvenience!

2022-10-09 16:20 UTC, closed without merging